development:
  dialect: mysql
  datasource: root:@tcp(mysql:3306)/go_api_tut_development?charset=utf8&parseTime=True&loc=Local
test:
  dialect: mysql
  datasource: root:@tcp(mysql:3306)/go_api_tut_test?charset=utf8&parseTime=True&loc=Local
