version: "3.9"

services:
  app:
    image: golang
    command: go run main.go
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/app
      - go-data:/go
    working_dir: /go/src/app
volumes:
  go-data:
