version: "3.9"

services:
  app:
    build: .
    command: air
    environment:
      GORM_DSN: root:@tcp(mysql:3306)/go_api_tut_development?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
      - go-data:/go
    working_dir: /workspace
  grpc:
    build: .
    command: go run pkg/grpc/server/main.go
    volumes:
      - .:/workspace
      - go-data:/go
    working_dir: /workspace
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: go_api_tut_development
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  go-data:
  mysql-data:
