version: "3.9"

services:
  app:
    image: golang
    command: go run main.go
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
      - go-data:/go
    working_dir: /workspace
volumes:
  go-data:
