version: "3.9"

services:
  app:
    image: golang
    command: go run main.go
    environment:
      GORM_DSN: root:@tcp(mysql:3306)/go_api_tut?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - .:/workspace
      - go-data:/go
    working_dir: /workspace
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: go_api_tut
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  go-data:
  mysql-data:
